steps:
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--path=.'
    id: Buildpack
    entrypoint: pack
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'
    id: Push
images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'

substitutions:
  _SERVICE_NAME: kuda-proxy